name: SiegePlugin
version: 1.0.3-PRE-2
api-version: 1.20
main: knockknockp.siegeplugin.SiegePlugin
permissions:
  gay:
    default: true
  lesbian:
    default: op
  siege.management:
    default: true
commands:
  menkissing:
    description: You like men kissing!
    usage: |
      /<command>
      /<command> <Player>:
    permission: gay
  siege:
    description: Manages siege mini game.
    usage: |
      /<command> wand: Gives player a wand.
      
      /<command> kit list: Lists all kits.
      /<command> kit create <Name>: Creates a kit that has a specified name.
      /<command> kit edit <Name>: Edits the contents of the kit.
      /<command> kit delete <Name>: Deletes the kit.
      /<command> kit get <Name>: Equips the specified kit.
      /<command> kit assigner <Name>: Creates the assigner that will give the player the specified kit when the mini game starts or respawns mid-game.
      
      /<command> team <Player> [red | blue]: Assigns the specified team to the specified player.
      /<command> assigner [red | blue]: Spawns an assigner of the specified team on the player's position.
      /<command> base <Coordinates> <Coordinates> [red | blue]: Assigns the area between two specified coordinates as a base of the specified team.
      /<command> wool <Coordinates> [0 | 1 | 2] [red | blue]: Assigns the specified coordinates as a wool of the specified team.
      /<command> deposit <Coordinates> [red | blue]: Assigns the specified coordinates as a wool deposit of the specified team.
      /<command> spawn <Coordinates> [red | blue]: Sets the specified coordinates as the spawn point for the specified team.
      
      /<command> team_chest <Coordinates> [neutral | red | blue]: Assigns the specified coordinates as a chest for the specified team.
      /<command> resetting_chest <Coordinates> <Reset cool down time in ticks> <Label...>: Assigns the specified coordinates as a chest with a reset cool down time of the specified ticks. The chest will reset to the content that was in the chest when it this command has been run. A specified label will be above the chest.
      /<command> unregister_chest <Coordinates>: Removes the specified chest from the mini game.
      
      /<command> time <Seconds>: Sets the time limit to the specified seconds. (Default: 10 minutes)
      
      /<command> start: Starts the mini game.
      /<command> stop: Stops and resets the mini game.
      /<command> full_reset: Resets all settings of the mini game.
      
      /<command> version: Prints plugin version.
      /<command> stats: Prints statistics.
    permission: siege.management
  test:
    permission: siege.management